### ISSUE TITLE
copy-and-paste bug in henry_serial.cc

### ISSUE THREAD

**Issue by jeffhammond** [CorySimon/ParallelForAllBlog#2]
In henry_serial.cc, lines 64-65, you dy should be dz.  This is a copy-and-paste bug.

If necessary, the trivial fix is found in https://github.com/jeffhammond/HenryCoefficient/commit/6ec0d41be3693822293a08b39eaee3ec18a12962.

**Comment by CorySimon** [comment]
Thank you, fixed in both the CPU and GPU codes.
